### ISSUE TITLE
Stolen

### ISSUE THREAD

**Issue by backslash** [MalavVyas/LinuxProcessInjection#1]
https://0x00sec.org/t/linux-infecting-running-processes/1097

Original Author, give credit when credit is due. Honestly shameless to just steal stuff and give zero credit. Zero respect

**Comment by MalavVyas** [comment]
1. This repository is a part of a blog I wrote for 1daylabs.ml

2. Stealing is where you claim someone's work as your own

3. Proper credits are mentioned on the blog

**Comment by MalavVyas** [comment]
As I said before, this repository was meant for just the blog, but a mistake on my part that I should have initialized a readme and mentioned important stuff like that there,
Thanks for bringing that to my attention
